### ISSUE TITLE
[question] How to insert images in Content field?

### ISSUE THREAD

**Issue by ooloth** [davidyeiser/airtable-nextjs-blog#1]
I’m intrigued by this blogging workflow!

I’m hoping to create something similar with Gatsby and just wondering how you managed to include images between the content paragraphs of some of your posts... 

Would you mind explaining how to do that using the AirTable “Long Text” field?

Here are a couple posts that alternate images and text:

1. https://davidyeiser.com/post/recSefJ6oGWCs57hd/bernheim-forest-giants
2. https://davidyeiser.com/post/rectyUMZZmFOsMs4N/type-friday-002

**Comment by davidyeiser** [comment]
Hey @ooloth — apologies for just getting back to you, I somehow missed this when it came through initially. No magic here unfortunately, I just uploaded the images to a my server and then once they were there I linked to them with normal markdown syntax.
